from __future__ import annotations

import json
import re
import subprocess
from collections import defaultdict
from pathlib import Path

from _common import load_config

# Only directories of near-identical records collapse; top-level results/ stays itemised.
COLLAPSE_DIRS = {"07_h5ad_shards", "20_convergence", "20_convergence_lr3e-4",
                 "21_lr_sweep", "pilot"}
ROLES = {
    "MANIFEST.md": "this file (generated)",
    "FULL_PACKAGE.md": "everything: comments, answers, decisions, mistakes, what failed",
    "REVIEWER_RESPONSES.md": "the drafted point-by-point response (hand-written prose)",
    "RESULTS_TABLES.md": "GENERATED from results/ - authoritative for every number",
    "EXPERIMENTS.md": "what each experiment measures and how to re-run it",
}


PIPELINE = [
    ("00_preshuffle_tahoe.py", "pre-shuffled Tahoe Zarr collection (298 GB)",
     "05, 06, 10, 20, 30"),
    ("01_build_label_tables.py", "global label tables for the four tasks", "10, 20"),
    ("02_build_eval_sets.py", "the two fixed held-out evaluation sets", "20"),
    ("03_verify_preshuffle.py", "check: the store is a permutation of the input", "-"),
    ("04_verify_loaders.py", "check: each strategy yields rows matching its indices", "-"),
    ("05_ondisk_structure.py", "on-disk run lengths per plate", "notebook section 3"),
    ("06_preshuffle_quality.py", "diversity vs shuffle_chunk_size", "notebook section 3"),
    ("08_microscopy_preshuffle_timing.py", "scPortrait pre-shuffling wall-clock",
     "notebook section 5"),
    ("10_batch_diversity.py", "minibatch diversity per strategy", "notebook sections 2, 3"),
    ("20_train_convergence.py", "training and validation histories, 62 runs",
     "notebook sections 1, 3"),
    ("30_throughput_sweeps.py", "throughput vs chunk size", "notebook sections 2, 3"),
    ("40_wgs_memmap_baselines.py", "the four memmap baselines", "notebook section 4"),
    ("41_wgs_preshuffle_timing.py", "WGS pre-shuffling wall-clock, three regimes",
     "notebook section 5"),
]


def main() -> None:
    cfg = load_config()
    root = Path(cfg["repo"]) / "revision"
    L: list[str] = []
    w = L.append

    rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                         cwd=root, capture_output=True, text=True).stdout.strip()
    w("# Revision manifest\n")
    w("Generated by `scripts/51_manifest.py` (re-run it after anything lands).")
    w(f"Git HEAD at generation: `{rev}`.\n")
    w("Read `docs/FULL_PACKAGE.md` first; `docs/RESULTS_TABLES.md` is generated")
    w("and is the authoritative source for numbers.\n")

    w("## Analysis scripts\n")
    w("How the notebook's inputs are produced, in order. The scripts carry no")
    w("docstrings, so this table is where they are described.\n")
    w("| script | produces | read by | lines |")
    w("|---|---|---|---:|")
    for name, makes, used_by in PIPELINE:
        f = root / "scripts" / name
        n = f.read_text().count(chr(10)) if f.exists() else 0
        w(f"| `{name}` | {makes} | {used_by} | {n} |")
    tooling = [f.name for f in sorted(root.glob("scripts/*.py"))
               if not f.name.startswith("_")
               and f.name not in {n for n, _, _ in PIPELINE}]
    if tooling:
        w("\nTooling run by `finalize.sh`: "
          + ", ".join(f"`{n}`" for n in tooling) + "\n")
    sup = sorted((root / "scripts" / "_superseded").glob("*.py"))
    if sup:
        w("\nArchived in `scripts/_superseded/`, no output reaches any deliverable: "
          + ", ".join(f"`{f.name}`" for f in sup) + "\n")
    w("\nShared helpers: " + ", ".join(
        f"`{f.name}`" for f in sorted(root.glob("scripts/_*.py"))) + "\n")

    w("## Job scripts\n")
    w("| sbatch | partition/qos | cpus | mem | time |")
    w("|---|---|---|---|---|")
    for f in sorted(root.glob("slurm/*.sbatch")):
        t = f.read_text()
        g = lambda p: (m.group(1) if (m := re.search(p, t)) else "-")  # noqa: E731
        w(f"| `{f.name}` | {g(r'-p (\S+)')}/{g(r'-q (\S+)')} | {g(r'--cpus-per-task=(\S+)')}"
          f" | {g(r'--mem=(\S+)')} | {g(r'--time=(\S+)')} |")

    w("\n## Result files\n")
    w("| result | experiment | rows | complete | failed arms |")
    w("|---|---|---:|---|---|")
    groups: dict[Path, list[Path]] = defaultdict(list)
    for f in sorted(root.glob("results/**/*.json")):
        groups[f.parent].append(f)
    for parent in sorted(groups):
        files = groups[parent]
        rel = parent.relative_to(root)
        if parent.name in COLLAPSE_DIRS:
            done = incomplete = 0
            for f in files:
                try:
                    b = json.loads(f.read_text())
                except Exception:
                    continue
                if b.get("complete") is False or b.get("completed_epoch") is False:
                    incomplete += 1
                else:
                    done += 1
            note = f"{done} complete" + (f", {incomplete} partial" if incomplete else "")
            w(f"| `{rel}/` *({len(files)} files)* | collapsed | - | {note} | - |")
            continue
        for f in files:
            try:
                b = json.loads(f.read_text())
            except Exception:
                continue
            if not isinstance(b, dict):
                continue
            n = len(b.get("results", b.get("val_history", [])))
            fa = b.get("failed_arms")
            fa = "none" if fa in ([], None) else str(fa)[:40]
            w(f"| `{f.relative_to(root)}` | {b.get('experiment', '')} | {n} "
              f"| {b.get('complete', b.get('completed_epoch', '-'))} | {fa} |")

    w("\n## Figures\n")
    for f in sorted(root.glob("figures/*.svg")):
        w(f"- `{f.relative_to(root)}` (+ `.png`)")

    w("\n## Documents\n")
    w("| document | lines | role |")
    w("|---|---:|---|")
    for f in sorted(root.glob("docs/*.md")) + [root / "README.md"]:
        w(f"| `{f.relative_to(root)}` | {f.read_text().count(chr(10))} "
          f"| {ROLES.get(f.name, 'entry point' if f.name == 'README.md' else '')} |")
    w("| `notebooks/revision_figures.ipynb` | - | executable figure notebook |")

    out = root / "docs" / "MANIFEST.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} ({len(L)} lines)")


if __name__ == "__main__":
    main()
